apiVersion: "v1"
kind: Pod
metadata:
  name: holi-dev-gpu
  namespace: proj-wud
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-H100-80GB-HBM3
                  # - NVIDIA-A100-SXM4-80GB
  runtimeClassName: nvidia
  imagePullSecrets:
    - name: artifact-registry-secret
  containers:
    - name: holi-dev-gpu-wan2-1
      image: us-docker.pkg.dev/engineering-380817/bdai/holi_gizmo:main
      imagePullPolicy: Always
      resources:
        limits:
          nvidia.com/gpu: 2
        requests:
          nvidia.com/gpu: 2
      command:
        - /bin/bash
      args:
        - "-c"
        - |
          echo "Successfully started" && \
          sleep infinity
      env:
        - name: OMP_NUM_THREADS
          value: "16"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        - name: EGL_LOG_LEVEL
          value: "debug"
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-api-key
              key: wandb-api-key
        - name: GH_TOKEN # environment variable will appear in the container
          valueFrom:
            secretKeyRef:
              name: github-token
              key: github-token
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /storage/nfs/
          name: wud-mounts
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: wud-mounts
      persistentVolumeClaim:
        claimName: proj-wud-cluster-root